# Generated by Django 4.2.15 on 2024-08-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='imagem',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
