# Generated by Django 4.2.15 on 2024-08-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livros_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='imagem',
            field=models.CharField(max_length=255),
        ),
    ]
